### ISSUE TITLE
フロント側からAPIを叩いてデータを取得する

### ISSUE THREAD

**Issue by yCroma** [t-sakurai816/inYourFreeTime#39]
# 概要(required)
仮の側のテンプレートができた。実際に作成していくために、フロント側からAPIを叩いてみる。Axiosなどの叩くツールかFetchを使う。

# 参考リンク

**Comment by t-sakurai816** [comment]
feature/#39 のブランチでカードに情報を載せるのやってみたので、参考にしてください
@yCroma

**Comment by yCroma** [comment]
#39 で要件満たしていると思うので、確認し次第マージしまーす。
ありがとうございまーす！！！

**Comment by t-sakurai816** [comment]
確認用のスクショです

<img width="1180" alt="ScreenShot 2021-07-22 13 31 17" src="https://user-images.githubusercontent.com/53470730/126590138-a37cf3cd-c30f-4605-ae92-1baf8db8e10d.png">
