### ISSUE TITLE
カードをクリックしたときに、itemページへ遷移する

### ISSUE THREAD

**Issue by yCroma** [t-sakurai816/inYourFreeTime#58]
# 概要(required)
IndexページとItemページをそれぞれ作成した。今度は、カードをクリックした際にitemページへ遷移するような処理を実装する。

# 参考リンク

**Comment by t-sakurai816** [comment]
できそうだったからやっちゃった
https://github.com/t-sakurai816/inYourFreeTime/pull/67/commits/6b04f028eee34edd4ca6fc1abf60b6acf2fbe209

**Comment by yCroma** [comment]
ありです。スマホから試して感動してました。明日のバイトも休みにしたので復帰次第頑張りやす😂😂😂
