### ISSUE TITLE
iconに機能をもたせる

### ISSUE THREAD

**Issue by t-sakurai816** [t-sakurai816/inYourFreeTime#68]
# 概要(required)

現在のiconはただ表示されているだけで、なんの意味もないものになっている。
シェアボタンなどに機能をもたせる。

**Comment by t-sakurai816** [comment]
Twitterアイコンを押すと共有できるようにしたけど、アイコンをタップするとカードが選択されてしまって、Twitterのリンクがクリックできない…
優先度とか調整できないのかな？

**Comment by yCroma** [comment]
選択肢は2つ

- 文字情報のグループを作って、そこをクリックした時に遷移するようにする
- z-indexとかで、アイコンたちの高さを高くするか、カードの高さを下げる

前者を取れば2秒で解決出来る。
後者はやってみんとわからん
そんな感じ

**Comment by t-sakurai816** [comment]
前者はどういう意味ですか？
カード自体をリンクにするのではなく、文字だけをリンクにするってこと？

**Comment by yCroma** [comment]
そう！文字列たちをdivとかで囲んで、それをリンクにする

**Comment by yCroma** [comment]
z-indexさくっとできるかも？

https://vuetifyjs.com/ja/components/overlays/#z-index

**Comment by t-sakurai816** [comment]
すみません。。
自分にはできないので、後お願いします…
そもそも、cardタップで画面遷移いらない気がしてきた
