### ISSUE TITLE
カードをタップして戻ったときの挙動を修正

### ISSUE THREAD

**Issue by t-sakurai816** [t-sakurai816/inYourFreeTime#69]
# 概要(required)

カードをタップすると、そのカードのページに飛べるようになった。
https://github.com/t-sakurai816/inYourFreeTime/pull/67/commits/6b04f028eee34edd4ca6fc1abf60b6acf2fbe209

しかし、ブラウザの戻るボタンをおすと、このように、header部分の下にカードが隠れてしまう
これを修正してしてください。

<img width="2133" alt="ScreenShot 2021-07-24 15 01 33" src="https://user-images.githubusercontent.com/53470730/126859151-44f55a05-0ab4-4f2b-be8e-9cc4d16f08b8.png">

**Comment by yCroma** [comment]
最悪clearfixで対応します

**Comment by t-sakurai816** [comment]
これ https://github.com/t-sakurai816/inYourFreeTime/commit/a1de471024c6be22cec6ce6de801627364d6e45d で何故か直りました。
`Item.vue`にheaderがもともとあって、それ消したらうまくいきました。
