### ISSUE TITLE
投稿時のプロパティ名と順序

### ISSUE THREAD

**Issue by yCroma** [t-sakurai816/inYourFreeTime#80]
# 概要(required)
WikiにあるAPIと順序やプロパティ名が異なっている。どのように統一するかを考える。

# 参考リンク

**Comment by t-sakurai816** [comment]
DBのキーはこんな感じです。
順序は適当でも、よしなにやってくれるので、気にしなくてよいですよ

<img width="1409" alt="ScreenShot 2021-07-25 10 24 57" src="https://user-images.githubusercontent.com/53470730/126884757-88aae69e-1702-4a6f-bb8c-74c7478c1c66.png">

**Comment by t-sakurai816** [comment]
id, createdAtは自動入力なので、気にしなくて良いです

**Comment by yCroma** [comment]
idとcreatedAtはいいんだけど、プログラムとwikiがずれているのが怖いのでそこをみてほしいっす

**Comment by t-sakurai816** [comment]
んん、、
nameじゃなくてuserNameにしてほしいかな
プログラムは今nameになっている

**Comment by yCroma** [comment]
そこらへんの話です。確認サンクス。可能であれば対応までお願いします。

**Comment by t-sakurai816** [comment]
対応しました

https://github.com/t-sakurai816/inYourFreeTime/commit/ba923cc8873fcd882bbf9d9d6faa3e3be9ac8c92
