### ISSUE TITLE
年齢や性別の入力方法や初期値

### ISSUE THREAD

**Issue by yCroma** [t-sakurai816/inYourFreeTime#82]
# 概要(required)
APIの仕様にもよるのだが、現在年齢や性別の初期値は空文字となっている。懸念要素としては、その場合「空の年齢」が発生してしまうのではないかと思った。よって、方針によっては入力していない時の初期値をnullにする必要がある。

# 参考リンク

**Comment by t-sakurai816** [comment]
![Uploading ScreenShot 2021-07-25 10.28.54.png…]()

**Comment by t-sakurai816** [comment]
現在はこのように空が入っています。
現状は特に困っていないけど、「if からの時 ~ をする」みたいな処理がしたくなるかもしれないので、null入れるようにしましょうか

<img width="1415" alt="ScreenShot 2021-07-25 10 29 21" src="https://user-images.githubusercontent.com/53470730/126884814-b04e5a09-dadb-4621-aa6a-60e8a57ead6e.png">

**Comment by yCroma** [comment]
#78 で対応します。
