### ISSUE TITLE
投稿画面のヒントやバリデーションの確認

### ISSUE THREAD

**Issue by yCroma** [t-sakurai816/inYourFreeTime#96]
# 概要(required)
@yCroma がとりあえずで実装したものなので、中身を見た上で設定してください。

# 参考リンク

**Comment by t-sakurai816** [comment]
- [ ] タイトル
- [ ] 説明
- [ ] 名前
- [ ] 年齢
- [ ] 性別

**Comment by t-sakurai816** [comment]
年齢OKでした
stringだとエラーになって、123歳以上だとエラーになることを確認しました
-3歳とかも怒られます

**Comment by t-sakurai816** [comment]
性別は選択式なのでOKD

**Comment by t-sakurai816** [comment]
タイトル、説明、年齢は最大文字数のバリデーションがされていないので、2000文字とか入力できてしまう…

**Comment by t-sakurai816** [comment]
# タイトル

最大文字数：30
Title is required. => 必須です！

# 説明

最大文字数：140（そのまま）
Desc is required. => 必須です！

# 名前

最大文字数：30
Name is required. => 必須です！

# 年齢

i don't belive you! => 0~122歳の間で入力してください！
